name: Push (main)

on:
  push:
    branches:
      - main
    paths:
      - "snap/snapcraft.yaml"
      - ".github/workflows/**.yaml"

jobs:
  build-and-test:
    uses: ./.github/workflows/build-and-test.yaml
